### ISSUE TITLE
Visualizacion de incidencias propias

### ISSUE THREAD

**Issue by Santiago-Pinto** [TDP2-Lucas-3/contame-mobile#21]
**Como** usuario de la aplicación Mobile
**Quiero** poder visualizar una lista de mis incidencias reportadas
**Para** poder realizar un seguimiento

**Criterios de aceptación:**
* **Cuando** el usuario accede a la pantalla de sus incidencias
**entonces** ve un listado de sus incidencias reportadas, con los campos: **Titulo**, **primera foto**, **fecha de publicación**, **estado (placeholder/label con color)**
  * Titulo en bold
  * fecha en formato: 'hace un dia'
* El listado esta ordenado por fecha de creación (de mas actual a mas antigua)
* Si no tiene imagen, mostramos un default, un icono de imagen tachado
* La lista tendra abajo a la derecha un boton '+' que permite crear una nueva incidencia
* Se mostraran todas las incidencias reportadas por el usuario hasta la fecha

![Screenshot_1603238261](https://user-images.githubusercontent.com/26676533/96656876-21f7de00-1317-11eb-898f-50b9bb468746.png)

**Comment by Azowyl** [comment]
30m

**Comment by Azowyl** [comment]
1h 30m

**Comment by Azowyl** [comment]
![Screenshot_1603238261](https://user-images.githubusercontent.com/26676533/96656769-efe67c00-1316-11eb-8650-91336a5b34d6.png)

**Comment by MatiasReimondo** [comment]
2h
