### ISSUE TITLE
Detalles de incidencia

### ISSUE THREAD

**Issue by Santiago-Pinto** [TDP2-Lucas-3/contame-mobile#23]
**Como** usuario de la aplicación Mobile
**Quiero** poder visualizar los detalles de una incidencia en especifico
**Para** poder visualizar detalles del mismo como: comentarios, imágenes, cantidad de votos

**Criterios de aceptación:**

*  **Cuando** el usuario va al listado de incidencias **y** hace click en una incidencia
    **entonces** se lo lleva a la vista de detalle y puede visualizar: titulo, descripción, un mapa reducido con la ubicación, imágenes
* Las imagenes se ven en tipo "Carrousel" al hacer swipe sobre la imagen del header
* Si no hay imagenes, en el header se muestra el mismo icono default que en el listado
* Si no hay descripcion el apartado "detalles" no se visualiza (ni el titulo)
* Si no hay ubicacion el apartado "ubicacion" se visualiza el icono junto al mensaje "no se especifico ubicacion" y el mapa **no** aparece
* Si hay ubicacion se muestra: localidad (en el mapa se ve el detalle)
* El titulo y la imagen funcionan como header "sticky", es decir, no scrollean. El resto es scrolleable
* La fecha aparece en formato "18 de octubre, 2020"
* El titulo no debe tener mas de 20 caracteres

![Android - 2](https://user-images.githubusercontent.com/26676533/96388814-c516ef00-1181-11eb-8e8d-1158ce636ec5.png) 
![Android - 3](https://user-images.githubusercontent.com/26676533/96388823-d233de00-1181-11eb-829f-b0948f7a970b.png)

**Comment by Azowyl** [comment]
30m

**Comment by MatiasReimondo** [comment]
El unico que me hace ruido es La fecha aparece en formato "18 de octubre" sin el anio
Me parece que el año podria llegar a ser un dato util para el usuario ya que podria tener reclamos similares de años distintos

**Comment by MatiasReimondo** [comment]
1h

**Comment by Azowyl** [comment]
1h

**Comment by Azowyl** [comment]
2h
