### ISSUE TITLE
Login con google

### ISSUE THREAD

**Issue by Santiago-Pinto** [TDP2-Lucas-3/contame-mobile#27]
**Como** usuario de la aplicación Mobile
**Quiero** poder acceder a la aplicación con mi cuenta de Google
**Para** poder acceder a la aplicación con facilidad

**Criterios de aceptación:**
- En la pantalla de login hay un boton para loguearse con google
- Al clickear el boton de login con google, aparece un modal de Google para seleccionar la cuenta para utilizar
- Si el usuario *no* selecciona una cuenta de Google, se le muestra un toast diciendole que debe seleccionar una cuenta para ingresar a la aplicación

**Caso de nuevo usuario**
- Al seleccionar una cuenta de Google satisfactoriamente, el usuario es presentado con una pantalla con su información para confirmar
- El usuario puede editar su información (nombre, apellido, foto), pero no su email
- Al confirmar su información, el usuario queda registrado e ingresa a la aplicación (se le muestra la pantalla de inicio)

**Caso usuario existente**
-  Al seleccionar una cuenta de Google satisfactoriamente, el usuario es autenticado e ingresa a la aplicación (se le muestra la pantalla de inicio)

* En caso de que el usuario este logueado y cerrara la aplicacion, al ingresar de nuevo, la aplicacion debe recordar las credenciales

![image](https://user-images.githubusercontent.com/19612265/97111651-d0f13c80-16be-11eb-9adb-b74fa2cdb3e1.png)
![image](https://user-images.githubusercontent.com/19612265/97121838-f05c8980-16ff-11eb-8e35-cebd11fc4f83.png)
![image](https://user-images.githubusercontent.com/19612265/97111653-d484c380-16be-11eb-9b78-7a0dfeee462b.png)

**Comment by lucaslavandeira** [comment]
Invertidas 3 horas en investigación + setup de integraciones con google en mobile

**Comment by MatiasReimondo** [comment]
Invertida 1h en la integracion de backend con google

**Comment by Azowyl** [comment]
30m en mockups

**Comment by Azowyl** [comment]
![Android - 3 (3)](https://user-images.githubusercontent.com/26676533/97091848-47396480-1615-11eb-8fa1-ffcd7cc44e9b.png)
![Android - 4 (1)](https://user-images.githubusercontent.com/26676533/97091842-37218500-1615-11eb-9b65-f8721767eb0c.png)

**Comment by lucaslavandeira** [comment]
+5 horas en desarrollo en confirmación de datos en el primer login

**Comment by lucaslavandeira** [comment]
+2 horas en rebase a master + implementación de mockups en la aplicación
