### ISSUE TITLE
Visualización de perfil

### ISSUE THREAD

**Issue by Santiago-Pinto** [TDP2-Lucas-3/contame-mobile#28]
**Como** usuario de la aplicación Mobile
**Quiero** poder visualizar mi perfil
**Para** poder validar mi información

**Criterios de aceptación:**
Luego de loguearse, al acceder a su perfil, el usuario va a visualizar: nombre, apellido, avatar y un email
Si el usuario no tiene foto de perfil, se muestra una foto por defecto (silueta de usuario)

**Comment by MatiasReimondo** [comment]
1h

**Comment by Azowyl** [comment]
1h

**Comment by lucaslavandeira** [comment]
4h para este ticket + #29
