### ISSUE TITLE
Integrar sistema de push notifications

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-mobile#43]
Integrar en el backend  + app mobile un sistema de push notifications: ante un evento determinado, el backend deberá poder mandar una notificación a determinado usuario (al dispositivo asociado a determinado usuario). Este primer issue es sólo para configurar el sistema necesario para llevar a cabo esta acción.

Esta librería que usa Firebase parece ser la solución más simple: https://github.com/zo0r/react-native-push-notification

Criterio de aceptación: Ante una acción (API call) al server, un usuario recibe una push notification en su celular. Puede ser cualquier mensaje, cualquier acción.

**Comment by Azowyl** [comment]
3h
