### ISSUE TITLE
Visualización de reportes en mobile

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-mobile#46]
Como usuario de la aplicación Mobile
Quiero poder visualizar la lista de los distintos reportes de forma ordenada siguiendo ciertos parámetros
Para poder encontrarlos mas rápidamente

Criterios de aceptación:
- Existe una pantalla de "incidencias" en donde el usuario puede ver todas las incidencias más recientes cargadas en el sistema, de todos los usuarios
- Estan ordenadas por fecha de creacion descendente (mas recientes primero)
- Sólo se muestran las primeras N **(a definir)** incidencias actualizadas más recientemente

**Comment by Azowyl** [comment]
1h30m
