### ISSUE TITLE
Filtros en mobile 

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-mobile#47]
**Como** usuario de la aplicación Mobile
**Quiero** poder buscar los distintos reportes siguiendo ciertos filtros
**Para** poder encontrarlos mas rápidamente

**Criterios de aceptación:.**
- En la pantalla de Incidencias (ver #46), agregar widgets que permitan:
  - Filtrar incidencias por zona (barrio)
  - Filtrar incidencias por categoría

- Al seleccionar uno de estos filtros, sólo se mostrarán las incidencias que cumplen con esa condición seleccionada. (Ej se selecciona barrio "Almagro" -> Sólo se muestran incidencias con ubicación en el barrio de Almagro)
- Al clickear en "Limpiar filtros" se muestran todas las incidencias nuevamente
- Se puede filtrar por varios barrios a la vez, y funcionan como un "or", es decir, seleccionan las incidencias que sean de un barrio ó del otro
- Se puede filtrar por varias categorias, y funcionan como un "or", es decir, seleccionan las incidencias que sean de un barrio ó del otro
- Si se combinan filtros, se tomara como "y", es decir, filtrar por categoria y un barrio, mostrara reportes de dicho barrio y dicha categoria

- Cuando se selecciona un filtro, se muestra un badge/chip con el filtro seleccionado y entre paréntesis la cantidad de ese tripo de filtros seleccionados. 
- En el badge de filtro anterior, existe una crucecita "x" para eliminar el filtro de la consulta.

- Si no se encuentran resultados de búsqueda con los filtros seleccionados, se le muestra un mensaje al usuario recomendandole sacar algunos filtros y reintentar nuevamente

![Android - 14](https://user-images.githubusercontent.com/26676533/98452124-429fa080-212b-11eb-9a85-4cfc08fdd06e.png)
![Android - 15](https://user-images.githubusercontent.com/26676533/98452127-46332780-212b-11eb-9c3e-d0ffad32cca9.png)

**Comment by Azowyl** [comment]
1h en mockups

**Comment by Azowyl** [comment]
2h

**Comment by Azowyl** [comment]
1h
