### ISSUE TITLE
Cambiar estado de reportes en backoffice

### ISSUE THREAD

**Issue by Azowyl** [TDP2-Lucas-3/contame-mobile#65]
Como administrador del Backoffice
Quiero cambiar el estado de los reportes
Para que reflejen el avance real de la reparación

**Comment by lucaslavandeira** [comment]
Issue moved to [TDP2-Lucas-3/TP0-Backend #4](https://github.com/TDP2-Lucas-3/TP0-Backend/issues/4) via [**ZenHub**](https://www.zenhub.com/)
