### ISSUE TITLE
Filtrar incidencias por estado

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-mobile#70]
**Como** usuario de la aplicación Mobile
**Quiero** poder filtrar por incidencias según estado
**Para** ver las incidencias qué están sólo en el estado que yo defino

## Criterios de aceptacion
* Se debe poder filtrar por estado
* Solo se listaran para filtrar los estados de incidencias presentes en el listado, es decir, si no existe una incidencia con estado "archivado", dicho estado no aparecera como opcion de filtro
* El filtro de estado funciona como "y" cuando es aplicado con otros tipos de filtros y como "o" cuando se filtra por mas de un estado

**Comment by Azowyl** [comment]
1h
