### ISSUE TITLE
Incidencias

### ISSUE THREAD

**Issue by Santiago-Pinto** [TDP2-Lucas-3/contame-mobile#8]
**Como** usuario de la aplicación Mobile
**Quiero** poder visualizar una lista de mis incidencias realizadas
**Para** poder realizar un seguimiento

**Criterios de aceptación:**

----------------------------------------------------------------------------------

**Como** usuario de la aplicación Mobile
**Quiero** poder visualizar los detalles de una incidencia en especifico
**Para** poder visualizar detalles del mismo como: comentarios, imágenes, cantidad de votos

**Criterios de aceptación:**

----------------------------------------------------------------------------------

**Como** usuario de la aplicación Mobile
**Quiero** poder dar de alta una nueva incidencia
**Para** poder notificar al gobierno de la incidencia ocurrida

**Criterios de aceptación:**
Un usuario puede reportar una incidencia con todos sus datos completos
Un usuario puede reportar una incidencia sin imagenes
Un usuario puede reportar una incidencia sin descripcion
El usuario observa las distintas categorias al reportar una incidencia
Al tener exito en la creacion se le muestra un mensaje (A definir)
Por default se muestra la posicion actual del usuario
Si tiene el GPS apagado se envia la ubicacion vacia
El usuario no puede crear una incidencia sin categoria ni Titulo (Que paso?)

----------------------------------------------------------------------------------

**Como** usuario del back office
**Quiero** poder visualizar todos los reportes existentes
**Para** poder visualizar detalles de los mismos

**Criterios de aceptación:**

  Se muestra un listado de incidentes con los campos: Titulo, Descripción, Ubicación (Lat,Lon), Lista de imagenes, Fecha de reporte, Fecha de ultima actualización, Fecha de cierre y categoria

**Comment by MatiasReimondo** [comment]
Una incidencia se compone de:
- Categoria
- Tilulo (Que paso? (60 caracteres))
- Descripcion (Mas detalle)
- Lista de imagenes
- Ubicacion (Lat, Lon)

De estos campos las imagenes, la descripcion y la ubicacion son opcionales

**Comment by MatiasReimondo** [comment]
Un usuario puede reportar una incidencia con todos sus datos completos
Un usuario puede reportar una incidencia sin imagenes
Un usuario puede reportar una incidencia sin descripcion
El usuario observa las distintas categorias al reportar una incidencia
Al tener exito en la creacion se le muestra un mensaje (A definir)
Por default se muestra la posicion actual del usuario
Si tiene el GPS apagado se envia la ubicacion vacia
El usuario no puede crear una incidencia sin categoria ni Titulo (Que paso?)

**Comment by MatiasReimondo** [comment]
El usuario puede subir una incidencia con mas de una imagen
